baseURL = 'https://hugo-test-hugo.netlify.app/'
languageCode = 'fr-fr'
title = 'Mon projet avec HugoCMS'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = "Accueil"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Le cas Yamal"
    url = "/posts/lamine-yamal/"
    weight = 2